# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 606)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 541, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.verticalLayoutWidget_2)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu_2.addAction(self.action_1)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menu_2.addAction(self.action_9)
        self.menu_3.addAction(self.action_10)
        self.menu_4.addAction(self.action_11)
        self.menu_4.addAction(self.action_12)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_2.setTitle(_translate("MainWindow", "Уровни"))
        self.menu_3.setTitle(_translate("MainWindow", "Правила"))
        self.menu_4.setTitle(_translate("MainWindow", "Смена темы"))
        self.action_1.setText(_translate("MainWindow", "Уровень 1"))
        self.action_4.setText(_translate("MainWindow", "Уровень 2"))
        self.action_7.setText(_translate("MainWindow", "Уровень 3"))
        self.action_8.setText(_translate("MainWindow", "Уровень 4"))
        self.action_9.setText(_translate("MainWindow", "Уровень 5"))
        self.action_10.setText(_translate("MainWindow", "Документация"))
        self.action_11.setText(_translate("MainWindow", "Чёрная"))
        self.action_12.setText(_translate("MainWindow", "Белая"))
    def add_functions(self, MainWindow):
        self.action_1.triggered.connect(lambda: self.start_level('Level1'))
        self.action_4.triggered.connect(lambda: self.start_level('Level2'))
        self.action_7.triggered.connect(lambda: self.start_level('Level3'))
        self.action_8.triggered.connect(lambda: self.start_level('Level4'))
        self.action_9.triggered.connect(lambda: self.start_level('Level5'))
        self.action_10.triggered.connect(lambda: self.message_box())
        self.action_11.triggered.connect(lambda: self.change_theme_black(MainWindow))
        self.action_12.triggered.connect(lambda: self.change_theme_white(MainWindow))

    def message_box(self):
        message_box = QMessageBox()

        message_box.setWindowTitle("Документация")
        message_box.setText(
            "Правила игры Cubicon: игра состоит из нескольких блоков, которые ты можешь перемещать главным блоком. Цель игры совместить блоки одного цвета. Игра состоит из нескольких уровней. Также есть стены через которые нельзя перетаскивать блоки и проходить главным блоком")
        message_box.setIcon(QMessageBox.Information)
        message_box.setStandardButtons(QMessageBox.Ok)
        message_box.exec_()

    def change_theme_black(self, MainWindow):
        MainWindow.setStyleSheet("background-color: grey;")

    def change_theme_white(self, MainWindow):
        MainWindow.setStyleSheet("background-color: white;")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
